name: InfernalMobs
main: io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs
version: 6.3
softdepend: [Vault, WizardlyMagic]
api-version: 1.16
author: Eliminator

commands:
  infernalmobs:
    aliases: [im]
    description: This is the infernal mobs base commands.
    usage: /<command>
    permission: infernal_mobs.commands
    permission-message: You don't have <permission>